name: ReachBack
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: 1.0.5
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  path: ^1.7.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "reachbackicon"
  ios: true
  image_path: "images/reachbackicon.png"

flutter:

  uses-material-design: true

  assets:
   - images/
